name: 'Continous Integration'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Substitude backend vars with secrets
        uses: cschleiden/replace-tokens@v1
        with:
          files: './devops/infrastructure/backend.tfvars'
        env: 
          tf_state_storage_account_name: ${{ secrets.TERRAFORM_STATE_STORAGE_ACCOUNT_NAME }}
          tf_state_storage_account_access_key: ${{ secrets.TERRAFORM_STATE_ACCESS_KEY }}

      - name: Terraform init
        id: init
        run: terraform init --backend-config=backend.tfvars

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Substitude variables file with secrets
        uses: cschleiden/replace-tokens@v1
        with:
          files: './devops/infrastructure/variables.tfvars'
        env: 
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          github_token: ${{ secrets.CUSTOM_GITHUB_PAT_TOKEN }}

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -var-file="variables.tfvars"

      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var-file="variables.tfvars" -auto-approve

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            }) 

  build:
    name: 'Build C# projects via dotnet'
    runs-on: ubuntu-latest
    env:
      AZURE_SYNC_FUNCTIONAPP_PACKAGE_PATH: 'src/Mikkelhm-F1.SyncFunctions'
      AZURE_API_FUNCTIONAPP_PACKAGE_PATH: 'src/Mikkelhm-F1.ApiFunctions'
      SYNC_FUNCTIONS_PACKAGE_NAME: 'sync-az-func.zip'
      API_FUNCTIONS_PACKAGE_NAME: 'api-az-func.zip'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: 'Build Sync functions project'
        shell: bash
        run: |
          pushd './${{ env.AZURE_SYNC_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish --configuration Release --output ./sync-functions-output
          cd ./sync-functions-output
          zip -r ${{ env.SYNC_FUNCTIONS_PACKAGE_NAME }} .
          popd
      - name: 'Build Api functions project'
        shell: bash
        run: |
          pushd './${{ env.AZURE_API_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish --configuration Release --output ./api-functions-output
          cd ./api-functions-output
          zip -r ${{ env.API_FUNCTIONS_PACKAGE_NAME }} .
          popd
      # Upload the code artifact, this will be used later
      - name: 'Package Sync Azure Function release build'
        uses: actions/upload-artifact@v3
        with:
          name: functions_sync_artifacts
          path: ${{ env.AZURE_SYNC_FUNCTIONAPP_PACKAGE_PATH }}/sync-functions-output/${{ env.SYNC_FUNCTIONS_PACKAGE_NAME }}
          if-no-files-found: error
      - name: 'Package Api Azure Function release build'
        uses: actions/upload-artifact@v3
        with:
          name: functions_api_artifacts
          path: ${{ env.AZURE_API_FUNCTIONAPP_PACKAGE_PATH }}/api-functions-output/${{ env.API_FUNCTIONS_PACKAGE_NAME }}
          if-no-files-found: error

  deploy:
    needs: [build, terraform]
    if: github.ref == 'refs/heads/main'
    name: 'Deploy to f1.madsn.dk'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: 'upload'
          # Directory location of the application source code
          app_location: 'src/mikkelhm-f1'
          # Required token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # Skips the build step for the application source code if set to true.
          skip_app_build: true

  deploy-sync-functions:
    needs: [build, terraform]
    uses: ./.github/workflows/deploy-functions.yml
    with:
      functions-name: 'Sync'
      build-output-path: '${{ github.workspace }}/build-artifacts'
      resource-group-name: '${{ secrets.AZURE_FUNCTIONS_SYNC_RESOURCE_GROUP_NAME }}'
      functions-app-name: '${{ secrets.AZURE_FUNCTIONS_SYNC_APP_NAME }}'
      functions-package-name: 'sync-az-func.zip'

  deploy-api-functions:
    needs: [build, terraform]
    uses: ./.github/workflows/deploy-functions.yml
    with:
      functions-name: 'Api'
      build-output-path: '${{ github.workspace }}/build-artifacts'
      resource-group-name: '${{ secrets.AZURE_FUNCTIONS_API_RESOURCE_GROUP_NAME }}'
      functions-app-name: '${{ secrets.AZURE_FUNCTIONS_API_APP_NAME }}'
      functions-package-name: 'api-az-func.zip'