name: 'Continous Integration'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Substitude backend vars with secrets
        uses: cschleiden/replace-tokens@v1
        with:
          files: './devops/infrastructure/backend.tfvars'
        env: 
          tf_state_storage_account_name: ${{ secrets.TERRAFORM_STATE_STORAGE_ACCOUNT_NAME }}
          tf_state_storage_account_access_key: ${{ secrets.TERRAFORM_STATE_ACCESS_KEY }}

      - name: Terraform init
        id: init
        run: terraform init --backend-config=backend.tfvars

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Substitude variables file with secrets
        uses: cschleiden/replace-tokens@v1
        with:
          files: './devops/infrastructure/variables.tfvars'
        env: 
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          github_token: ${{ secrets.CUSTOM_GITHUB_PAT_TOKEN }}

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -var-file="variables.tfvars"

      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var-file="variables.tfvars" -auto-approve

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            }) 

  build:
    name: 'Build C# projects via dotnet'
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Mikkelhm-F1.Functions'
      FUNCTIONS_PACKAGE_NAME: 'az-func.zip'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: 'Build functions project'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./functions-output
          zip -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/${{ env.FUNCTIONS_PACKAGE_NAME }} ./functions-output
          popd
      # Upload the code artifact, this will be used later
      - name: 'Package Azure Function release build'
        uses: actions/upload-artifact@v2
        with:
          name: functions_artifacts
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          if-no-files-found: error

  deploy:
    needs: [build, terraform]
    if: github.ref == 'refs/heads/main'
    name: 'Deploy to f1.madsn.dk'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Mikkelhm-F1.Functions'
      AZURE_RESOURCE_GROUP_NAME: 'mikkelhm-f1'
      AZURE_FUNCTIONAPP_NAME: 'mikkelhm-f1-functions-app'
      FUNCTIONS_PACKAGE_NAME: 'az-func.zip'

    permissions:
          id-token: write
          contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: 'upload'
          # Directory location of the application source code
          app_location: 'src/mikkelhm-f1'
          # Required token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # Skips the build step for the application source code if set to true.
          skip_app_build: true

      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true

      - name: 'Fetching Azure Functions Publishing Profile'
        id: fncapp
        uses: azure/powershell@v1
        with:
          inlineScript: |
              $profile = ""
              $profile = Get-AzWebAppPublishingProfile -ResourceGroupName $env:AZURE_RESOURCE_GROUP_NAME -Name $env:AZURE_FUNCTIONAPP_NAME
              $profile = $profile.Replace("`r", "").Replace("`n", "")
              Write-Output "::set-output name=pubprofile::$profile"
              Remove-Variable profile
          azPSVersion: "latest"

      # Fetch published code
      - name: 'Download Azure function release build'
        uses: actions/download-artifact@v2
        with:
          name: functions_artifacts
          path: ${{ env.BUILD_OUTPUT_PATH }}

      - name: Depoy the functions app
        uses: Azure/functions-action@v1
        with:
          app-name: mikkelhm-f1-functions-app
          package: ${{ env.BUILD_OUTPUT_PATH }}/${{ env.FUNCTIONS_PACKAGE_NAME }}
          publish-profile: ${{ steps.fncapp.outputs.pubprofile }}